name: Cambridge University India Society
author: Anik Roy
email: anik545@gmail.com

# links
facebook: https://www.facebook.com/indiasoc
facebook_events: https://www.facebook.com/pg/indiasoc/events
instagram: https://www.instagram.com/cuindiasoc/?hl=en
email: mailto:india@cusu.cam.ac.uk


collections:
  - committee
  - sponsors