backend:
  name: git-gateway


media_folder: "img/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: 'pages'
    label: 'Pages'
    editor:
      preview: true
    files:
      - label: 'Home Page'
        name: 'index'
        file: 'index.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'Home' }
          - { label: 'Layout', name: 'title', widget: 'hidden', default: 'index' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Committee'
        name: 'committee'
        file: 'committee.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'Committee' }
          - { label: 'Layout', name: 'title', widget: 'hidden', default: 'committee' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Charities'
        name: 'charities'
        file: 'charities.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'Charities' }
          - { label: 'Layout', name: 'title', widget: 'hidden', default: 'charities' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Sponsors'
        name: 'sponsors'
        file: 'sponsors.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'Sponsors' }
          - { label: 'Layout', name: 'title', widget: 'hidden', default: 'sponsors' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      